config/routes.rb
Rails.application.routes.draw do
  #resources :comments
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', 
        path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  
  resources :portfolios, except: [:show] do 
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me',  to: 'pages#about'
  get 'contact',   to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do 
    member do 
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'
  
  root 'pages#home'

 
  
 # get 'pages/home'
 # get 'pages/about'
 # get 'pages/contact'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies, dependent: :destroy

  accepts_nested_attributes_for :technologies, 
                                allow_destroy: true,
                                reject_if: lambda{ |attrs| attrs['name'].blank? }

  validates :title, presence: true, length: { minimum: 5 } 

  validates :body, presence: true

  #validates :main_image, :thumb_image, presence: true

  #after_initialize :set_defaults  

  #include Placeholder

  # scope :angular, ->{where(subtitle: "Angular")}
  # scope :sorted,  ->{order("created_at DESC")}
  # scope :ruby_on_rails_portfolio_items, ->{where(subtitle: "Ruby on Rails")}
  # Same as below:

  mount_uploader :main_image, PortfolioUploader
  mount_uploader :thumb_image, PortfolioUploader

  def self.angular
    where(subtitle: "Angular")
  end

  def self.ruby_on_rails_portfolio_items 
    where(subtitle: "Ruby on Rails")
  end

  def self.sorted 
    order("created_at DESC")
  end

  def self.by_position 
    order("position ASC")
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController

  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  #before_action :find_portfolio_item, only: [:show, :edit, :update, :destroy]

  layout "portfolio"

  def index
    # @portfolio_items = Portfolio.all.order("created_at DESC")
    # @portfolio_items = Portfolio.angular.sorted
    # @portfolio_items = Portfolio.ruby_on_rails_portfolio_items.sorted
    @portfolio_items = Portfolio.by_position 
    #byebug
    respond_to do |format|
      format.html       
      format.json { render(json: @portfolio_items) }
      format.js
    end    #render(layout: false)
  end

  def sort 
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    render body: nil
  end

  def angular 
    @angular_portfolio_items = Portfolio.angular.sorted
  end

  def show 
    find_portfolio_item
  end

  def new
    @portfolio_item = Portfolio.new
    #3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
     #byebug
    respond_to do |format|
      if @portfolio_item.save
        format.html {redirect_to(portfolios_path, notice: "Your post is now live.")}
        format.json { render(json: @portfolio_item) }
        format.js
      else
        format.html {render('new')}
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
    
  end

  def edit
    find_portfolio_item
  end

  def destroy
    find_portfolio_item 
    @portfolio_item.destroy

    respond_to do |format|
      format.html { redirect_to(portfolios_path, notice: 'Record was removed.') }
      format.json { head :no_content }
      format.js
    end 
  end

  def update 
    find_portfolio_item
    respond_to do |format|
      #byebug
      if @portfolio_item.update_attributes(portfolio_params)
        
        format.html { redirect_to(portfolios_path, notice: 'Blog was successfully updated.') }

        format.json {render(:show, status: :ok, location: @portfolio_item)}
        format.js
      else
        format.html {render(:edit)}
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
    
  end

  private

    def find_portfolio_item
      @portfolio_item = Portfolio.find(params[:id])
      return @portfolio_item
    end
    def portfolio_params 
      params.require(:portfolio).permit(:title, 
                                        :subtitle, 
                                        :body, 
                                        :main_image,
                                        :thumb_image,
                                        :technologies_attributes => [:id, :name, :_destroy])
    end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

  def generate_image(height:, width:) 
    return "http://via.placeholder.com/#{height}x#{width}"
  end

  def portfolio_img(img, type)
    #byebug
    if img.model.main_image? || img.model.thumb_image? 
      return img 
    elsif type=='thumb'
      generate_image(height:'356', width:'280')
    elsif type=='main'
      generate_image(height:'600', width:'400')
    end
  end

  def set_defaults
    self.main_image  ||= generate_image(600, 400)
    self.thumb_image ||= generate_image(356, 280)

    #self.main_image  ||= "http://via.placeholder.com/600x400"
    #self.thumb_image ||= "http://via.placeholder.com/350x200" 

   ## if self.main_image == nil 
      #self.main_image = "http://via.placeholder.com/600x400"
    #end
  ##  if
    # self.thumb_image ||= "http://via.placeholder.com/350x200"
    #end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio_item) do |f| %>
  <% if portfolio_item.errors.any? %> 
    <% portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator(error) %>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label(:title) %>
        <%= f.text_field(:title,class:"form-control") %>
      </div>

      <div class="form-group">
        <%= f.label(:subttitle) %>
        <%= f.text_field(:subtitle,class:"form-control") %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file <%= f.file_field(:main_image, style:'display:none;') %>
        </label>        
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a thumb image file <%= f.file_field(:thumb_image, style:'display:none;') %>
        </label>
      </div>

    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label(:body) %>
        <%= f.text_area(:body,class:"form-control", rows: 13) %>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <hr>

    <h2>Technologies Used:</h2>
    <div>
      <%= f.fields_for(:technologies)  do |technology_form|%>
        <%= render('technology_fields', f: technology_form) %>
      <% end %>
      <div>
        <%= link_to_add_association('Add Technology',f, :technologies) %>
      </div>
    </div>
    <br>
    <div class="actions">
      <%= f.submit("Save Portfolio Item", class:"btn btn-primary btn-block") %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card" data-id="<%= portfolio_item.id %>">
    <div class="portfolio-item-border">    
      <%= link_to(
          image_tag("#{portfolio_img(portfolio_item.thumb_image,'thumb')}" ,width: '100%'), 
          portfolio_show_path(portfolio_item)          
          ) 
          #portfolio_img(portfolio_item.thumb_image,'thumb')
          #image_tag("#{portfolio_img(portfolio_item.thumb_image,'thumb')}" ,width: '100%') #, 
          #portfolio_show_path(portfolio_item))
          %>  
    </div>  
    
    <p class="card-text">
      <span><%= link_to(portfolio_item.title, portfolio_show_path(portfolio_item)) %> </span><%= portfolio_item.subtitle %>
    </p>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label(:name) %>
  <%= f.text_field(:name,class:"form-control") %>
  <%= link_to_remove_association('Remove Technology', f) %>
</div>
  

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items </h1>

<%= link_to("Create New Item", new_portfolio_path) if logged_in?(:site_admin) %><br />

<% @angular_portfolio_items.each do |portfolio_item|%>
  <%= link_to(image_tag(portfolio_item.thumb_image), portfolio_show_path(portfolio_item)) unless portfolio_item.thumb_image.nil? %>
  <h3><%= link_to(portfolio_item.title, portfolio_show_path(portfolio_item)) %></h3>
  <h4><%= portfolio_item.subtitle %></h4>
  <p><%= truncate(portfolio_item.body, length: 100) %></p>
  
  <p><%= link_to("show", portfolio_show_path(portfolio_item)) %></p>  
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit Portfolio</h1>
  <%# <%= render('form') > %>
  <%= render('form', portfolio_item: @portfolio_item) %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
     <%= source_helper('alert alert-warning') %>

    <div class="row <%='sortable' if logged_in?(:site_admin) %>">
      <%= render(partial: 'portfolio_item', collection: @portfolio_items) %>
    </div> 
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a New Item </h1>
  <%# <%= render('form') > %>
  <%= render('form', portfolio_item: @portfolio_item) %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-6">
         <%= image_tag("#{portfolio_img(@portfolio_item.main_image,'main')}" ,width: '80%')
        %> 

    </div>
    <div class="col-md-6">
      <h1><%= @portfolio_item.title %></h1>

      <hr>

      <em><%= @portfolio_item.subtitle %></em>

      <hr>

      <p><%=  @portfolio_item.body %></p>

      <hr>

      <h2>Technologies Used:</h2>

      <% @portfolio_item.technologies.each do |t| %>
        <p><%= t.name %></p>
      <% end %>

      <% if logged_in?(:site_admin) %>
        <div class="col-md-12">
          <hr>
          <%#  <!--a href="/portfolios/<%= portfolio_item.id >"></a --> %>        
            <p>
              <%=link_to("Edit Item", edit_portfolio_path(@portfolio_item), class:'btn btn-warning') %>   
              <%=link_to("Delete", @portfolio_item, method: :delete, data: {confirm: "Are you sure?"}, class:'btn btn-danger') %>
            </p>       
        </div>
      <% end %> 

    </div>     
  </div>
</div>








<%# <%= #params.inspect > %>


<%# <%= #session.inspect > %>